[[task]]
  id = "dev"
  type = "long"
  dependencies = ["build"]
  cmd = "../../bin/dungeon"

[[task]]
  id = "start"
  type = "long"
  cmd = "../../bin/dungeon"

[[task]]
  id = "build"
  type = "short"
  dependencies = ["templ", "build-css", "build-js"]
  watch = ["**/*.go", "*.go"]
  env = { SQLITE_ENABLE_LOCKING_STYLE = "1" }
  cmd = "go build -o ../../bin/ ."

[[task]]
  id = "templ"
  type = "short"
  watch = ["**/*.templ"]
  cmd = "go tool templ generate ./server/"

[[task]]
  id = "build-css"
  type = "short"
  watch = [
    "css/*.css",
    "server/*.templ"
  ]
  dependencies = ["install-css"]
  cmd = """
    cd css
    npx tailwindcss \
      -i ./index.css \
      -o ../server/static/index.css
  """

[[task]]
  id = "install-css"
  type = "short"
  cmd = "cd css && npm install"

[[task]]
  id = "build-js"
  type = "short"
  dependencies = ["install-ts"]
  watch = ["ts/*.ts", "ts/**/*.ts"]
  cmd = """
    cd ts
    node -e "require('esbuild').buildSync({entryPoints:['index.ts'],bundle:true,outfile:'../server/static/index.js'})"
  """

[[task]]
  id = "install-ts"
  type = "short"
  cmd = "cd ts && npm install"

[[task]]
  id = "tidy"
  type = "short"
  cmd = "go mod tidy -e"

[[task]]
  id = "generate"
  type = "short"
  dependencies = ["tidy"]
