[[task]]
  id = "dev"
  type = "long"
  watch = ["**/*", "*"]
  cmd = "cd $MONKS_ROOT && SQLITE_ENABLE_LOCKING_STYLE=1 go run ./apps/air -mode=serve"

[[task]]
  id = "build"
  type = "short"
  cmd = "cd $MONKS_ROOT && SQLITE_ENABLE_LOCKING_STYLE=1 go build -o ./bin/ ./apps/air"

[[task]]
  id = "start"
  type = "long"
  cmd = "cd $MONKS_ROOT && ./bin/air -mode=serve"

