[[task]]
  id = "dev"
  type = "long"
  watch = ["**/*", "*"]
  cmd = "cd $MONKS_ROOT && go run ./apps/air -mode=serve"

[[task]]
  id = "build"
  type = "short"
  cmd = "cd $MONKS_ROOT && go build -o ./bin/ ./apps/air"

[[task]]
  id = "start"
  type = "long"
  cmd = "cd $MONKS_ROOT && ./bin/air -mode=serve"

