[[task]]
  id = "dev"
  type = "long"
  dependencies = ["build"]
  cmd = "../../bin/breadcrumbs"

[[task]]
  id = "start"
  type = "long"
  cmd = "../../bin/breadcrumbs"

[[task]]
  id = "build"
  type = "short"
  watch = ["**/*.go", "*.go"]
  env = { SQLITE_ENABLE_LOCKING_STYLE = "1" }
  cmd = "go build -o ../../bin/ ."

[[task]]
  id = "tidy"
  type = "short"
  cmd = "go mod tidy -e"

[[task]]
  id = "generate"
  type = "short"
  dependencies = ["tidy"]
  cmd = "protoc --go_out=. --go_opt=module=monks.co/apps/breadcrumbs proto/breadcrumbs.proto proto/vector_tile.proto"
