[[task]]
  id = "dev"
  type = "long"
  dependencies = ["build"]
  cmd = "../../bin/breadcrumbs"

[[task]]
  id = "start"
  type = "long"
  cmd = "../../bin/breadcrumbs"

[[task]]
  id = "build"
  type = "short"
  watch = ["**/*.go", "*.go"]
  env = { SQLITE_ENABLE_LOCKING_STYLE = "1" }
  cmd = "go build -o ../../bin/ ."

[[task]]
  id = "tidy"
  type = "short"
  cmd = "go mod tidy -e"

[[task]]
  id = "xcframework"
  type = "short"
  cmd = "go tool gomobile init && rm -rf ios/Mobile.xcframework && GOWORK=off go tool gomobile bind -target ios,iossimulator -o ios/Mobile.xcframework ./mobile"
  dependencies = ["protoc", "tidy"]

[[task]]
  id = "protoc"
  type = "short"
  cmd = "protoc --go_out=. --go_opt=module=monks.co/apps/breadcrumbs proto/breadcrumbs.proto proto/vector_tile.proto"

[[task]]
  id = "generate"
  type = "short"
  dependencies = ["tidy", "protoc", "xcframework"]
