app = "monks-go"
kill_signal = "SIGINT"
kill_timeout = 15
primary_region = "ord"

[build]
  dockerfile = "Dockerfile"

[env]
  MONKS_ROOT="/app"
  MONKS_DATA="/data"

[[mounts]]
  source = "data"
  destination = "/data"

[[vm]]
  size = "shared-cpu-8x"
  memory = "16gb"

[[services]]
  protocol = "tcp"
  processes = ["app"]
  internal_port = 8080

  [[services.ports]]
    port = 80
    handlers = ["proxy_proto"]

  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

[[services]]
  protocol = "tcp"
  processes = ["app"]
  internal_port = 4433

  [[services.ports]]
    port = 443
    handlers = ["proxy_proto"]

  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

