[[task]]
  id = "dev"
  type = "long"
  dependencies = ["build"]
  cmd = "../../bin/dolmenwood"

[[task]]
  id = "start"
  type = "long"
  cmd = "../../bin/dolmenwood"

[[task]]
  id = "build"
  type = "short"
  dependencies = ["templ"]
  watch = ["**/*.go", "*.go"]
  env = { SQLITE_ENABLE_LOCKING_STYLE = "1" }
  cmd = "go build -o ../../bin/ ."

[[task]]
  id = "templ"
  type = "short"
  watch = ["**/*.templ"]
  cmd = "go tool templ generate ./server/"
