[[task]]
  id = "dev"
  type = "long"
  dependencies = ["build"]
  cmd = "../../bin/creamery serve"

[[task]]
  id = "start"
  type = "long"
  cmd = "../../bin/creamery serve"

[[task]]
  id = "build"
  type = "short"
  watch = ["**/*.go", "*.go", "*.tmpl"]
  dependencies = ["compile-pegs"]
  cmd = "go build -o ../../bin/creamery ./cmd"

[[task]]
  id = "compile-pegs"
  type = "short"
  watch = ["batchparser/*.peg", "fdaparser/*.peg"]
  cmd = """
    go tool peg -inline batchparser/batch.peg || exit 1
    go tool peg -inline fdaparser/fda.peg || exit 1
  """
