[[task]]
  id = "templ"
  type = "short"
  cmd = "go run github.com/a-h/templ/cmd/templ generate"
  watch = ["*.templ"]

[[task]]
  id = "dev"
  type = "long"
  cmd = "cd $MONKS_ROOT && go run ./apps/posts -port=3009"
  watch = [
    "**/*.go",
    "*.go",
    "posts/*.md",
  ]
  dependencies = [
    "templ"
  ]

[[task]]
  id = "build"
  type = "short"
  cmd = "cd $MONKS_ROOT && go build -o ./bin/ ./apps/posts"
  dependencies = [
    "templ"
  ]

[[task]]
  id = "start"
  type = "long"
  cmd = "cd $MONKS_ROOT && ./bin/posts -port=3009"

