[[task]]
  id = "build"
  type = "short"
  dependencies = ["generate", "build-js"]
  watch = ["**/*.go", "*.go"]
  cmd = "go build -o ../../bin/ ."

[[task]]
  id = "generate"
  type = "short"
  cmd = "go tool templ generate"
  watch = ["**/*.templ"]

[[task]]
  id = "install-ts"
  type = "short"
  cmd = "cd ts && npm install"

[[task]]
  id = "build-js"
  type = "short"
  dependencies = ["install-ts"]
  watch = ["ts/*.ts"]
  cmd = """
    cd ts
    node -e "require('esbuild').buildSync({entryPoints:['index.ts'],bundle:true,outfile:'../static/index.js'})"
  """

[[task]]
  id = "dev"
  type = "long"
  dependencies = ["build"]
  cmd = "../../bin/ci"

[[task]]
  id = "start"
  type = "long"
  cmd = "../../bin/ci"

[[task]]
  id = "build-images"
  type = "short"
  dependencies = ["build-base-image", "build-builder-image"]
  cmd = "echo 'done'"

[[task]]
  id = "build-base-image"
  type = "short"
  cmd = "fly deploy --build-only --push -c base.fly.toml"

[[task]]
  id = "build-builder-image"
  type = "short"
  cmd = "fly deploy --build-only --push -c builder.fly.toml"
