[[task]]
  id = "build"
  type = "short"
  watch = ["**/*.go", "*.go"]
  env = { SQLITE_ENABLE_LOCKING_STYLE = "1" }
  cmd = "go build -o ../../bin/ ."

[[task]]
  id = "dev"
  type = "long"
  dependencies = ["build"]
  cmd = "../../bin/tagtime"

[[task]]
  id = "tidy"
  type = "short"
  cmd = "go mod tidy -e"

[[task]]
  id = "xcframework"
  type = "short"
  cmd = "test \"$(uname)\" = Darwin && go tool gomobile init && rm -rf ios/Mobile.xcframework && go tool gomobile bind -target ios,iossimulator -o ios/Mobile.xcframework ./mobile || echo 'skipping xcframework (not macOS)'"

[[task]]
  id = "generate"
  type = "short"
  dependencies = ["xcframework"]
