[[task]]
  id = "templ"
  type = "short"
  watch = ["*.templ"]
  cmd = "go tool templ generate ."

[[task]]
  id = 'test'
  type = 'short'
  dependencies = [
    'go-test',
    'go-vet',
    'gofix',
    'staticcheck',
    'govulncheck',
  ]

[[task]]
  id = 'go-test'
  type = 'short'
  dependencies = ['templ']
  cmd = 'go test ./...'

[[task]]
  id = 'go-vet'
  type = 'short'
  dependencies = ['templ']
  cmd = 'go vet ./...'

[[task]]
  id = 'gofix'
  type = 'short'
  dependencies = ['templ']
  cmd = 'test -z "$(go fix -diff ./...)"'

[[task]]
  id = 'staticcheck'
  type = 'short'
  dependencies = ['templ']
  cmd = 'go tool staticcheck ./...'

[[task]]
  id = 'govulncheck'
  type = 'short'
  dependencies = ['templ']
  cmd = 'go tool govulncheck ./...'
