[[task]]
  id = "convert-zones"
  type = "short"
  cmd = "fish convert-zones.fish"

[[task]]
  id = "install"
  type = "short"
  cmd = "cd terraform && terraform init"

[[task]]
  id = "format"
  type = "short"
  cmd = "terraform fmt"
  dependencies = ["convert-zones"]

[[task]]
  id = "plan"
  type = "short"
  cmd = "cd terraform && terraform plan"
  dependencies = ["convert-zones"]

[[task]]
  id = "apply"
  type = "short"
  cmd = "cd terraform && yes yes | terraform apply"
  dependencies = ["convert-zones"]
