[[task]]
  id = "aws-convert-zones"
  type = "short"
  cmd = "fish convert-zones.fish"

[[task]]
  id = "fmt"
  type = "short"
  dependencies = [
    "aws-convert-zones"
  ]
  cmd = "source .envrc && cd terraform && terraform fmt"

[[task]]
  id = "init"
  type = "short"
  cmd = "source .envrc && cd terraform && terraform init"

[[task]]
  id = "plan"
  type = "short"
  dependencies = [
    "aws-convert-zones"
  ]
  cmd = "source .envrc && cd terraform && terraform plan"

[[task]]
  id = "apply"
  type = "short"
  dependencies = [
    "aws-convert-zones"
  ]
  cmd = "source .envrc && cd terraform && yes yes | terraform apply"

