[[task]]
  id = "dev"
  type = "long"
  dependencies = ["build"]
  cmd = "../../bin/errlog"

[[task]]
  id = "start"
  type = "long"
  cmd = "../../bin/errlog"

[[task]]
  id = "build"
  type = "short"
  watch = ["**/*.go", "*.go"]
  env = { SQLITE_ENABLE_LOCKING_STYLE = "1" }
  cmd = "go build -o ../../bin/ ."

