[[task]]
  id = "dev"
  type = "long"
  watch = [
    "**/*.go", "*.go",
    "**/*.gohtml", "*.gohtml",
  ]
  cmd = "SQLITE_ENABLE_LOCKING_STYLE=1 go run ."
  dependencies = ["build-css"]

[[task]]
  id = "build"
  type = "short"
  cmd = "cd $MONKS_ROOT && SQLITE_ENABLE_LOCKING_STYLE=1 go build -o ./bin/ ./apps/traffic"
  dependencies = ["build-css"]

[[task]]
  id = "start"
  type = "long"
  cmd = "$MONKS_ROOT/bin/traffic"

[[task]]
  id = "build-css"
  type = "short"
  dependencies = ["install-css"]
  watch = [
    "css/*.css",
    "templates/*.gohtml"
  ]
  cmd = """
    cd css
    npx tailwindcss \
      -i ./index.css \
      -o ../static/index.css
  """

[[task]]
  id = "install-css"
  type = "short"
  cmd = "cd css && npm install"

