[[task]]
  id = "dev"
  type = "long"
  cmd = "cd $MONKS_ROOT && go run ./apps/traffic -port=3008"

[[task]]
  id = "build"
  type = "short"
  cmd = "cd $MONKS_ROOT && go build -o ./bin/ ./apps/traffic"

[[task]]
  id = "start"
  type = "long"
  cmd = "cd $MONKS_ROOT && ./bin/traffic -port=3008"

