[defaults]
  region = "ord"
  vm_size = "shared-cpu-1x"
  vm_memory = "256"

[apps.air]
  [[apps.air.routes]]
    path = "air"
    host = "thor"
    access = "autogroup:member"

[apps.aranet]
  [[apps.aranet.routes]]
    path = "aranet"
    host = "brigid"
    access = "tag:service"

[apps.calendar]
  [[apps.calendar.routes]]
    path = "calendar"
    host = "brigid"
    access = "ajm@passkey"

[apps.ci]
  packages = ["sqlite"]

  [[apps.ci.routes]]
    path = "ci"
    host = "fly"
    access = "tag:service"

  [[apps.ci.routes]]
    path = "ci"
    host = "fly"
    access = "ajm@passkey"

[apps.creamery]
  [[apps.creamery.routes]]
    path = "creamery"
    host = "brigid"
    access = "ajm@passkey"

[apps.directory]
  [[apps.directory.routes]]
    path = "directory"
    host = "brigid"
    access = "ajm@passkey"

[apps.dogs]
  vm_size = "shared-cpu-2x"
  vm_memory = "1gb"
  packages = ["sqlite"]

  [[apps.dogs.routes]]
    path = "dogs"
    host = "fly"
    access = "autogroup:danger-all"

  [[apps.dogs.routes]]
    path = "dogs"
    host = "thor"
    access = "ajm@passkey"

[apps.dolmenwood]
  [[apps.dolmenwood.routes]]
    path = "dolmenwood"
    host = "brigid"
    access = "ajm@passkey"

[apps.dungeon]
  [[apps.dungeon.routes]]
    path = "dungeon"
    host = "brigid"
    access = "autogroup:danger-all"

[apps.golink]
  [[apps.golink.routes]]
    path = "golink"
    host = "brigid"
    access = "ajm@passkey"

[apps.homepage]
  [[apps.homepage.routes]]
    path = "homepage"
    host = "fly"
    access = "autogroup:danger-all"

  [[apps.homepage.routes]]
    path = "homepage"
    host = "brigid"
    access = "ajm@passkey"

[apps.logs]
  vm_size = "shared-cpu-4x"
  vm_memory = "2gb"
  packages = ["sqlite"]

  [[apps.logs.routes]]
    path = "logs"
    host = "fly"
    access = "tag:service"

  [[apps.logs.routes]]
    path = "logs"
    host = "fly"
    access = "ajm@passkey"

[apps.mailer]
  [[apps.mailer.routes]]
    path = "mailer"
    host = "fly"
    access = "tag:service"

[apps.map]
  packages = ["sqlite"]

  [[apps.map.routes]]
    path = "map"
    host = "fly"
    access = "autogroup:danger-all"

  [[apps.map.routes]]
    path = "map"
    host = "brigid"
    access = "ajm@passkey"

[apps.monitor]
  [[apps.monitor.routes]]
    path = "monitor"
    host = "thor"
    access = "tag:service"

[apps.movies]
  [[apps.movies.routes]]
    path = "movies"
    host = "thor"
    access = "autogroup:member"

  [[apps.movies.routes]]
    path = "movies"
    host = "thor"
    access = "ajm@passkey"
    capabilities = ["movies-write"]

[apps.ping]
  [[apps.ping.routes]]
    path = "ping"
    host = "brigid"
    access = "ajm@passkey"

[apps.proxy]
  public = true
  vm_size = "shared-cpu-8x"
  vm_memory = "2gb"
  packages = ["iptables", "ip6tables", "sqlite"]
  files = ["config/proxy.toml", "apps/proxy/static/"]
  cmd = ["/app/app", "-machine", "fly"]

  [[apps.proxy.routes]]
    path = "proxy"
    host = "fly"
    access = "tag:service"

[apps.reddit]
  [[apps.reddit.routes]]
    path = "reddit"
    host = "thor"
    access = "ajm@passkey"

[apps.scrobbles]
  [[apps.scrobbles.routes]]
    path = "scrobbles"
    host = "brigid"
    access = "ajm@passkey"

[apps.sms]
  [[apps.sms.routes]]
    path = "sms"
    host = "brigid"
    access = "tag:service"

[apps.writing]
  vm_size = "shared-cpu-4x"
  vm_memory = "2gb"
  files = ["apps/writing/writing/"]

  [[apps.writing.routes]]
    path = "writing"
    host = "fly"
    access = "autogroup:danger-all"

  [[apps.writing.routes]]
    path = "writing"
    host = "brigid"
    access = "ajm@passkey"

[apps.youtube]
  [[apps.youtube.routes]]
    path = "youtube"
    host = "brigid"
    access = "ajm@passkey"
