mode = "dev"

[[service]]
  type = "redirect-to-https"
  addr = "0.0.0.0:80"

[[service]]
  type = "https"
  addr = "0.0.0.0:443"
  [service.rewrites]
    "/" = "/homepage/"
  [service.apps]
    golink = "monks-golink-brigid"
    map = "monks-map-brigid"
    ping = "monks-ping-brigid"
    writing = "monks-writing-brigid"
    sms = "monks-sms-brigid"
    traffic = "monks-traffic-brigid"
    youtube = "monks-youtube-brigid"
    directory = "monks-directory-brigid"
    homepage = "monks-homepage-brigid"
    dogs = "monks-dogs-brigid"
    scrobbles = "monks-scrobbles-brigid"
    calendar = "monks-calendar-brigid"
    aranet = "monks-aranet-brigid"

[acme]
  storage_path = "cache"
  production = true
  domains = ["brigid.ss.cx"]

  [[acme.strategies]]
    strategy = "dns"

