mode = "dev"

[[service]]
  type = "redirect-to-https"
  addr = "100.103.217.4:80"

[[service]]
  type = "https"
  addr = "100.103.217.4:443"
  apps = [
    "golink",
    "map",
    "ping",
    "posts",
    "sms",
    "traffic",
    "youtube",
    "directory"
  ]

[acme]
  storage_path = "cache"
  production = true
  domains = ["brigid.ss.cx"]

  [[acme.strategies]]
    strategy = "dns"

