mode = "dev"

[[service]]
  type = "redirect-to-https"
  addr = "0.0.0.0:80"

[[service]]
  type = "https"
  addr = "0.0.0.0:443"
  apps = [
    "golink",
    "map",
    "ping",
    "writing",
    "sms",
    "traffic",
    "errlog",
    "youtube",
    "directory",
    "homepage",
    "dogs",
    "scrobbles"
  ]
  [service.rewrites]
    "/" = "/homepage/"

[acme]
  storage_path = "cache"
  production = true
  domains = ["brigid.ss.cx"]

  [[acme.strategies]]
    strategy = "dns"

