[defaults]
  region = "ord"
  vm_size = "shared-cpu-1x"
  vm_memory = "256"

[apps.proxy]
  vm_memory = "512"
  volume = "monks_proxy_data"
  public = true
  packages = ["iptables", "ip6tables", "sqlite"]
  files = ["config/fly.toml", "apps/proxy/static/"]
  cmd = ["/app/bin/app", "-machine", "fly"]

[apps.homepage]
  volume = "monks_homepage_data"

[apps.writing]
  vm_size = "shared-cpu-4x"
  vm_memory = "2gb"
  volume = "monks_writing_data"
  files = ["apps/writing/writing/"]

[apps.dogs]
  vm_size = "shared-cpu-2x"
  vm_memory = "1gb"
  volume = "monks_dogs_data"
  packages = ["sqlite"]

[apps.logs]
  vm_memory = "512"
  volume = "monks_logs_data"
  packages = ["sqlite"]

[apps.errlog]
  volume = "monks_errlog_data"
  packages = ["sqlite"]

[apps.map]
  volume = "monks_map_data"
  packages = ["sqlite"]

[apps.mailer]
  volume = "monks_mailer_data"
