[redirects]
  "belgianman.com" = "https://belgianman.bandcamp.com/"
  "blgn.mn"        = "https://belgianman.bandcamp.com/"

  "amonks.co"         = "https://monks.co/"
  "andrewmonks.com"   = "https://monks.co/"
  "andrewmonks.net"   = "https://monks.co/"
  "andrewmonks.org"   = "https://monks.co/"
  "docrimes.com"      = "https://monks.co/"
  "fmail.email"       = "https://monks.co/"
  "fuckedcars.com"    = "https://monks.co/"
  "lyrics.gy"         = "https://monks.co/"
  "needsyourhelp.org" = "https://monks.co/"
  "popefucker.com"    = "https://monks.co/"
  "ss.cx"             = "https://monks.co/"

[acme]
  storage_path = "/data"
  production = true
  domains = [
    "monks.co",

    "belgianman.com",
    "blgn.mn",

    "amonks.co",
    "andrewmonks.com",
    "andrewmonks.net",
    "andrewmonks.org",
    "docrimes.com",
    "fmail.email",
    "fuckedcars.com",
    "lyrics.gy",
    "needsyourhelp.org",
    # "popefucker.com",
    "ss.cx"
  ]

  [[acme.strategies]]
    strategy = "dns"

[[service]]
  type = "redirect-to-https"
  addr = "0.0.0.0:8080"

[[service]]
  type = "https"
  addr = "0.0.0.0:4433"
  rewrites = { "/" = "/homepage/" }


