default_mirror = "github.com/amonks/go"

[[package]]
dir = "pkg/migrate"

[[package]]
dir = "pkg/llm"

[[package]]
dir = "pkg/agent"

[[package]]
dir = "pkg/jj"

[[package]]
dir = "pkg/set"

[[package]]
dir = "cmd/beetman"
module_path = "monks.co/beetman"
mirror = "github.com/amonks/beetman"

[[package]]
dir = "cmd/ww"
module_path = "monks.co/ww"
mirror = "github.com/amonks/ww"

[[package]]
dir = "cmd/incrementum"
module_path = "monks.co/incrementum"
mirror = "github.com/amonks/incrementum"

[[package]]
dir = "cmd/rootsync"
module_path = "monks.co/rootsync"
mirror = "github.com/amonks/rootsync"

[[package]]
dir = "cmd/backupd"
module_path = "monks.co/backupd"
mirror = "github.com/amonks/backupd"

[[package]]
dir = "cmd/run"
module_path = "monks.co/run"
mirror = "github.com/amonks/run"
version = "1.0.0-beta"
