mode = "dev"

[[service]]
  type = "redirect-to-https"
  addr = "0.0.0.0:80"

[[service]]
  type = "https"
  addr = "0.0.0.0:443"
  apps = [
    "air",
    "traffic",
    "movies",
    "reddit",
    "dogs",
    "monitor"
  ]
  extra_routes = { "genres" = 9999 }

[acme]
  storage_path = "cache"
  production = true
  domains = ["thor.ss.cx"]

  [[acme.strategies]]
    strategy = "dns"

