[[task]]
  id = "dev"
  type = "long"
  dependencies = ["build"]
  cmd = "../../bin/map"

[[task]]
  id = "start"
  type = "long"
  cmd = "../../bin/map"
  watch = ["./static/index.css"]

[[task]]
  id = "build"
  type = "short"
  watch = ["**/*.go", "*.go"]
  dependencies = ["build-css", "build-js"]
  env = { SQLITE_ENABLE_LOCKING_STYLE = "1" }
  cmd = "go build -o ../../bin/ ."

[[task]]
  id = "build-css"
  type = "short"
  watch = [
    "css/*.css",
    "templates/*.gohtml"
  ]
  dependencies = ["install-css"]
  cmd = """
    cd css
    npx tailwindcss \
      -i ./index.css \
      -o ../static/index.css
  """

[[task]]
  id = "install-css"
  type = "short"
  cmd = "cd css && npm install"

[[task]]
  id = "build-js"
  type = "short"
  dependencies = ["install-ts"]
  cmd = """
    cd ts
    node -e "require('esbuild').buildSync({entryPoints:['index.ts'],bundle:true,outfile:'../static/index.js'})"
  """

[[task]]
  id = "install-ts"
  type = "short"
  cmd = "cd ts && npm install"

