[[task]]
  id = "dev"
  type = "long"
  cmd = "go run . -port=3006"
  watch = ["**/*.go", "*.go"]
  dependencies = ["build-css"]

[[task]]
  id = "build"
  type = "short"
  dependencies = ["build-css"]
  cmd = "cd $MONKS_ROOT && go build -o ./bin/ ./apps/map"

[[task]]
  id = "start"
  type = "long"
  cmd = "$MONKS_ROOT/bin/map -port=3006"

[[task]]
  id = "build-css"
  type = "short"
  dependencies = ["install-css"]
  watch = [
    "css/*.css",
    "templates/*.gohtml"
  ]
  cmd = """
    cd css
    npx tailwindcss \
      -i ./index.css \
      -o ../static/index.css
  """

[[task]]
  id = "install-css"
  type = "short"
  cmd = "cd css && npm install"

