package main

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/pelletier/go-toml/v2"
	"monks.co/pkg/env"
)

type flyAppsConfig struct {
	Defaults flyAppDefaults         `toml:"defaults"`
	Apps     map[string]flyAppEntry `toml:"apps"`
}

type flyAppDefaults struct {
	Region   string `toml:"region"`
	VMSize   string `toml:"vm_size"`
	VMMemory string `toml:"vm_memory"`
}

type flyAppEntry struct {
	VMSize   string   `toml:"vm_size"`
	VMMemory string   `toml:"vm_memory"`
	Volume   string   `toml:"volume"`
	Public   bool     `toml:"public"`
	Packages []string `toml:"packages"`
	Files    []string `toml:"files"`
	Cmd      []string `toml:"cmd"`
}

func generateFlyConfigs() error {
	path := env.InMonksRoot("config", "fly-apps.toml")
	bs, err := os.ReadFile(path)
	if err != nil {
		return fmt.Errorf("reading fly-apps config: %w", err)
	}
	var cfg flyAppsConfig
	if err := toml.Unmarshal(bs, &cfg); err != nil {
		return fmt.Errorf("parsing fly-apps config: %w", err)
	}

	names := make([]string, 0, len(cfg.Apps))
	for name := range cfg.Apps {
		names = append(names, name)
	}
	sort.Strings(names)

	for _, name := range names {
		app := cfg.Apps[name]
		dir := env.InMonksRoot("apps", name)

		dockerfile := buildDockerfile(name, app, cfg.Defaults)
		if err := writeGenerated(filepath.Join(dir, "Dockerfile.fly"), dockerfile); err != nil {
			return fmt.Errorf("writing Dockerfile for %s: %w", name, err)
		}

		flytoml := buildFlyToml(name, app, cfg.Defaults)
		if err := writeGenerated(filepath.Join(dir, "fly.toml"), flytoml); err != nil {
			return fmt.Errorf("writing fly.toml for %s: %w", name, err)
		}

		dockerignore := buildDockerignore(name)
		if err := writeGenerated(filepath.Join(dir, "Dockerfile.fly.dockerignore"), dockerignore); err != nil {
			return fmt.Errorf("writing Dockerfile.fly.dockerignore for %s: %w", name, err)
		}
	}

	return nil
}

func buildDockerfile(name string, app flyAppEntry, defaults flyAppDefaults) string {
	var b strings.Builder

	b.WriteString("# Generated by taskmaker - DO NOT EDIT.\n\n")

	// Build stage (identical for all apps).
	b.WriteString("FROM golang:alpine AS gobuild\n")
	b.WriteString("  ENV MONKS_ROOT=/app\n")
	b.WriteString("  RUN apk update && apk add build-base gcc bash nodejs npm\n")
	b.WriteString("  RUN go install github.com/amonks/run/cmd/run@latest\n")
	b.WriteString("  WORKDIR /app\n")
	b.WriteString("  COPY go.mod go.sum ./\n")
	b.WriteString("  RUN go mod download\n")
	b.WriteString("  RUN CGO_ENABLED=1 go build github.com/mattn/go-sqlite3\n")
	b.WriteString("  COPY . .\n")
	fmt.Fprintf(&b, "  WORKDIR /app/apps/%s\n", name)
	b.WriteString("  RUN --mount=type=cache,target=/root/.cache/go-build run build\n")
	b.WriteString("\n")

	// Runtime stage (per-app).
	b.WriteString("FROM alpine\n")
	packages := "ca-certificates"
	if len(app.Packages) > 0 {
		packages += " " + strings.Join(app.Packages, " ")
	}
	fmt.Fprintf(&b, "  RUN apk add --no-cache %s\n", packages)
	fmt.Fprintf(&b, "  WORKDIR /app/apps/%s\n", name)
	fmt.Fprintf(&b, "  COPY --from=gobuild /app/bin/%s /app/bin/app\n", name)
	for _, f := range app.Files {
		// Copy runtime files directly from build context, not through the build stage.
		fmt.Fprintf(&b, "  COPY %s /app/%s\n", f, f)
	}
	b.WriteString("  ENV MONKS_ROOT=/app\n")
	if app.Volume != "" {
		b.WriteString("  ENV MONKS_DATA=/data\n")
	} else {
		b.WriteString("  ENV MONKS_DATA=/tmp\n")
	}
	b.WriteString("  ENV TSNET_FORCE_LOGIN=1\n")

	cmd := app.Cmd
	if len(cmd) == 0 {
		cmd = []string{"/app/bin/app"}
	}
	quoted := make([]string, len(cmd))
	for i, arg := range cmd {
		quoted[i] = fmt.Sprintf("%q", arg)
	}
	fmt.Fprintf(&b, "  CMD [%s]\n", strings.Join(quoted, ", "))

	return b.String()
}

func buildFlyToml(name string, app flyAppEntry, defaults flyAppDefaults) string {
	region := defaults.Region
	vmSize := defaults.VMSize
	if app.VMSize != "" {
		vmSize = app.VMSize
	}
	vmMemory := defaults.VMMemory
	if app.VMMemory != "" {
		vmMemory = app.VMMemory
	}

	var b strings.Builder

	b.WriteString("# Generated by taskmaker - DO NOT EDIT.\n\n")
	fmt.Fprintf(&b, "app = %q\n", "monks-"+name)
	fmt.Fprintf(&b, "primary_region = %q\n", region)
	b.WriteString("\n")

	b.WriteString("[build]\n")
	fmt.Fprintf(&b, "  dockerfile = %q\n", "Dockerfile.fly")
	fmt.Fprintf(&b, "  ignorefile = %q\n", "apps/"+name+"/Dockerfile.fly.dockerignore")
	b.WriteString("\n")

	b.WriteString("[env]\n")
	fmt.Fprintf(&b, "  MONKS_APP_NAME = %q\n", name)
	b.WriteString("  MONKS_ROOT = \"/app\"\n")
	if app.Volume != "" {
		b.WriteString("  MONKS_DATA = \"/data\"\n")
	} else {
		b.WriteString("  MONKS_DATA = \"/tmp\"\n")
	}
	b.WriteString("  TSNET_FORCE_LOGIN = \"1\"\n")
	b.WriteString("\n")

	b.WriteString("[[vm]]\n")
	fmt.Fprintf(&b, "  size = %q\n", vmSize)
	fmt.Fprintf(&b, "  memory = \"%s\"\n", vmMemory)

	if app.Volume != "" {
		b.WriteString("\n")
		b.WriteString("[[mounts]]\n")
		fmt.Fprintf(&b, "  source = %q\n", app.Volume)
		b.WriteString("  destination = \"/data\"\n")
	}

	if app.Public {
		b.WriteString("\n")
		b.WriteString("[[services]]\n")
		b.WriteString("  internal_port = 4433\n")
		b.WriteString("  protocol = \"tcp\"\n")
		b.WriteString("  [[services.ports]]\n")
		b.WriteString("    port = 443\n")
		b.WriteString("    handlers = [\"proxy_proto\"]\n")
		b.WriteString("\n")
		b.WriteString("[[services]]\n")
		b.WriteString("  internal_port = 8080\n")
		b.WriteString("  protocol = \"tcp\"\n")
		b.WriteString("  [[services.ports]]\n")
		b.WriteString("    port = 80\n")
		b.WriteString("    handlers = [\"proxy_proto\"]\n")
		b.WriteString("\n")
		b.WriteString("[metrics]\n")
		b.WriteString("  port = 9999\n")
		b.WriteString("  path = \"/metrics\"\n")
	}

	return b.String()
}

func buildDockerignore(name string) string {
	var b strings.Builder
	b.WriteString("# Generated by taskmaker - DO NOT EDIT.\n\n")
	b.WriteString("cache\n")
	b.WriteString(".git\n")
	b.WriteString(".jj\n")
	b.WriteString(".envrc\n")
	b.WriteString("bin\n")
	b.WriteString("data\n")
	b.WriteString("aws/terraform\n")
	b.WriteString("apps/dogs/archive.zip\n")
	b.WriteString("\n")
	b.WriteString("# exclude all other apps\n")
	b.WriteString("apps/*\n")
	fmt.Fprintf(&b, "!apps/%s\n", name)
	b.WriteString("\n")
	b.WriteString("# exclude build artifacts\n")
	b.WriteString("**/node_modules\n")
	return b.String()
}

func writeGenerated(path string, content string) error {
	return os.WriteFile(path, []byte(content), 0644)
}
