[[task]]
  id = "dev"
  type = "long"
  watch = ["**/*.go", "*.go"]
  cmd = "SQLITE_ENABLE_LOCKING_STYLE=1 go run ."

[[task]]
  id = "build"
  type = "short"
  cmd = "SQLITE_ENABLE_LOCKING_STYLE=1 go build -o ../../bin/ ."

[[task]]
  id = "start"
  type = "long"
  cmd = "../../bin/template"

