[[task]]
  id = "templ"
  type = "short"
  cmd = "go run github.com/a-h/templ/cmd/templ generate"
  watch = ["*.templ"]

[[task]]
  id = "dev"
  type = "long"
  watch = ["**/*", "*"]
  cmd = "SQLITE_ENABLE_LOCKING_STYLE=1 go run ."

[[task]]
  id = "build"
  type = "short"
  cmd = "SQLITE_ENABLE_LOCKING_STYLE=1 go build -o ../../bin/ ."
  dependencies = ["templ"]

[[task]]
  id = "start"
  type = "long"
  cmd = "../../bin/directory"

