[[task]]
  id = "build"
  type = "short"
  cmd = "go run github.com/a-h/templ/cmd/templ generate"

[[task]]
  id = "dev"
  type = "long"
  cmd = "go run github.com/a-h/templ/cmd/templ generate -watch"
