storage_path = "/data"

[[apps]]
  name = "places"
  path = "/places/"
  is_public = true

[[apps]]
  name = "weblog"
  path = "/"
  is_public = true

[[services]]
  port = 8080
  protocol = "http"
  is_admin = false

[[services]]
  port = 4433
  protocol = "https"
  is_admin = false
  [services.acme]
    storage_path = "/data/acme"
    production = true
    domains = ["belgianman.com", "blgn.mn", "monks.co", "monks-go.fly.dev"]
    [[services.acme.strategies]]
      strategy = "alpn"
      external_port = 443
      internal_port = 4433
