storage_path = "./data"

[[apps]]
  name = "places"
  path = "/places/"
  is_public = false

[[apps]]
  name = "weblog"
  path = "/"
  is_public = false

[[apps]]
  name = "ping"
  path = "/ping/"
  is_public = false

[[services]]
  port = 1337
  protocol = "http"
  is_admin = false

[[services]]
  port = 443
  protocol = "https"
  is_admin = false
  [services.acme]
    production = true
    domains = ["brigid.ss.cx"]
    [[services.acme.strategies]]
      strategy = "dns"

