[[task]]
  id = "dev"
  type = "long"
  watch = ["**/*", "*"]
  cmd = "go run . -port=3013"

[[task]]
  id = "build"
  type = "short"
  cmd = "go build -o ../../bin/ ."

[[task]]
  id = "start"
  type = "long"
  cmd = "../../bin/mailer -port=3013"


